# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_connector_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_connector_service.proto',
  package='telemetry.connectors',
  syntax='proto3',
  serialized_pb=_b('\n\x1c\x64\x61ta_connector_service.proto\x12\x14telemetry.connectors\" \n\x11VinAllowedRequest\x12\x0b\n\x03Vin\x18\x01 \x01(\t\"%\n\x12VinAllowedResponse\x12\x0f\n\x07\x41llowed\x18\x01 \x01(\x08\x32q\n\x0eVehicleService\x12_\n\nVinAllowed\x12\'.telemetry.connectors.VinAllowedRequest\x1a(.telemetry.connectors.VinAllowedResponseB/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3')
)




_VINALLOWEDREQUEST = _descriptor.Descriptor(
  name='VinAllowedRequest',
  full_name='telemetry.connectors.VinAllowedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Vin', full_name='telemetry.connectors.VinAllowedRequest.Vin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=86,
)


_VINALLOWEDRESPONSE = _descriptor.Descriptor(
  name='VinAllowedResponse',
  full_name='telemetry.connectors.VinAllowedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Allowed', full_name='telemetry.connectors.VinAllowedResponse.Allowed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['VinAllowedRequest'] = _VINALLOWEDREQUEST
DESCRIPTOR.message_types_by_name['VinAllowedResponse'] = _VINALLOWEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VinAllowedRequest = _reflection.GeneratedProtocolMessageType('VinAllowedRequest', (_message.Message,), dict(
  DESCRIPTOR = _VINALLOWEDREQUEST,
  __module__ = 'data_connector_service_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.connectors.VinAllowedRequest)
  ))
_sym_db.RegisterMessage(VinAllowedRequest)

VinAllowedResponse = _reflection.GeneratedProtocolMessageType('VinAllowedResponse', (_message.Message,), dict(
  DESCRIPTOR = _VINALLOWEDRESPONSE,
  __module__ = 'data_connector_service_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.connectors.VinAllowedResponse)
  ))
_sym_db.RegisterMessage(VinAllowedResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-github.com/teslamotors/fleet-telemetry/protos'))

_VEHICLESERVICE = _descriptor.ServiceDescriptor(
  name='VehicleService',
  full_name='telemetry.connectors.VehicleService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=127,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='VinAllowed',
    full_name='telemetry.connectors.VehicleService.VinAllowed',
    index=0,
    containing_service=None,
    input_type=_VINALLOWEDREQUEST,
    output_type=_VINALLOWEDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VEHICLESERVICE)

DESCRIPTOR.services_by_name['VehicleService'] = _VEHICLESERVICE

# @@protoc_insertion_point(module_scope)
