# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_connector_service_pb2 as data__connector__service__pb2


class VehicleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.VinAllowed = channel.unary_unary(
        '/telemetry.connectors.VehicleService/VinAllowed',
        request_serializer=data__connector__service__pb2.VinAllowedRequest.SerializeToString,
        response_deserializer=data__connector__service__pb2.VinAllowedResponse.FromString,
        )


class VehicleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def VinAllowed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'VinAllowed': grpc.unary_unary_rpc_method_handler(
          servicer.VinAllowed,
          request_deserializer=data__connector__service__pb2.VinAllowedRequest.FromString,
          response_serializer=data__connector__service__pb2.VinAllowedResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'telemetry.connectors.VehicleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
