# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle_alert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicle_alert.proto',
  package='telemetry.vehicle_alerts',
  syntax='proto3',
  serialized_pb=_b('\n\x13vehicle_alert.proto\x12\x18telemetry.vehicle_alerts\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n\rVehicleAlerts\x12\x36\n\x06\x61lerts\x18\x01 \x03(\x0b\x32&.telemetry.vehicle_alerts.VehicleAlert\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03vin\x18\x03 \x01(\t\"\xb1\x01\n\x0cVehicleAlert\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\taudiences\x18\x02 \x03(\x0e\x32\".telemetry.vehicle_alerts.Audience\x12.\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nded_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*B\n\x08\x41udience\x12\x0b\n\x07Unknown\x10\x00\x12\x0c\n\x08\x43ustomer\x10\x01\x12\x0b\n\x07Service\x10\x02\x12\x0e\n\nServiceFix\x10\x03\x42/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_AUDIENCE = _descriptor.EnumDescriptor(
  name='Audience',
  full_name='telemetry.vehicle_alerts.Audience',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Customer', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Service', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ServiceFix', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=397,
  serialized_end=463,
)
_sym_db.RegisterEnumDescriptor(_AUDIENCE)

Audience = enum_type_wrapper.EnumTypeWrapper(_AUDIENCE)
Unknown = 0
Customer = 1
Service = 2
ServiceFix = 3



_VEHICLEALERTS = _descriptor.Descriptor(
  name='VehicleAlerts',
  full_name='telemetry.vehicle_alerts.VehicleAlerts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alerts', full_name='telemetry.vehicle_alerts.VehicleAlerts.alerts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='telemetry.vehicle_alerts.VehicleAlerts.created_at', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vin', full_name='telemetry.vehicle_alerts.VehicleAlerts.vin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=215,
)


_VEHICLEALERT = _descriptor.Descriptor(
  name='VehicleAlert',
  full_name='telemetry.vehicle_alerts.VehicleAlert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='telemetry.vehicle_alerts.VehicleAlert.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audiences', full_name='telemetry.vehicle_alerts.VehicleAlert.audiences', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='started_at', full_name='telemetry.vehicle_alerts.VehicleAlert.started_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ended_at', full_name='telemetry.vehicle_alerts.VehicleAlert.ended_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=395,
)

_VEHICLEALERTS.fields_by_name['alerts'].message_type = _VEHICLEALERT
_VEHICLEALERTS.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_VEHICLEALERT.fields_by_name['audiences'].enum_type = _AUDIENCE
_VEHICLEALERT.fields_by_name['started_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_VEHICLEALERT.fields_by_name['ended_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['VehicleAlerts'] = _VEHICLEALERTS
DESCRIPTOR.message_types_by_name['VehicleAlert'] = _VEHICLEALERT
DESCRIPTOR.enum_types_by_name['Audience'] = _AUDIENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleAlerts = _reflection.GeneratedProtocolMessageType('VehicleAlerts', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLEALERTS,
  __module__ = 'vehicle_alert_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.vehicle_alerts.VehicleAlerts)
  ))
_sym_db.RegisterMessage(VehicleAlerts)

VehicleAlert = _reflection.GeneratedProtocolMessageType('VehicleAlert', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLEALERT,
  __module__ = 'vehicle_alert_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.vehicle_alerts.VehicleAlert)
  ))
_sym_db.RegisterMessage(VehicleAlert)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z-github.com/teslamotors/fleet-telemetry/protos'))
# @@protoc_insertion_point(module_scope)
