#!/bin/bash
# Fleet Telemetry - PostgreSQL Quick Start Script
# This file shows the commands to get PostgreSQL + Fleet Telemetry running

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   Fleet Telemetry + PostgreSQL - Quick Start Guide        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# OPTION 1: Docker Compose (Recommended)
echo "📦 OPTION 1: Docker Compose (Simplest - Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Build the Docker image (one-time)"
echo "  docker build -t fleet-telemetry-integration-tests:latest ."
echo ""
echo "Step 2: Generate TLS certificates (one-time)"
echo "  go run tools/main.go"
echo ""
echo "Step 3: Start PostgreSQL and Fleet Telemetry"
echo "  docker-compose -f docker-compose.postgres.yml up -d"
echo ""
echo "Step 4: Verify it's running"
echo "  docker-compose -f docker-compose.postgres.yml ps"
echo ""
echo "Step 5: Check the logs"
echo "  docker-compose -f docker-compose.postgres.yml logs -f app"
echo ""
echo "Step 6: Access the services"
echo "  Status:  http://localhost:8080/status"
echo "  Metrics: http://localhost:8000/metrics"
echo "  DB:      localhost:5432"
echo "    psql -h localhost -U telemetry_user -d fleet_telemetry"
echo ""
echo "Step 7: Stop everything"
echo "  docker-compose -f docker-compose.postgres.yml down"
echo ""
echo ""

# OPTION 2: Manual Setup
echo "🔧 OPTION 2: Manual Setup (Linux/Mac)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Install PostgreSQL"
echo "  Ubuntu: sudo apt install -y postgresql postgresql-contrib"
echo "  macOS:  brew install postgresql"
echo ""
echo "Step 2: Create database and user"
echo "  sudo -u postgres psql << EOF"
echo "  CREATE DATABASE fleet_telemetry;"
echo "  CREATE USER telemetry_user WITH PASSWORD 'telemetry_password';"
echo "  GRANT ALL PRIVILEGES ON DATABASE fleet_telemetry TO telemetry_user;"
echo "  \\c fleet_telemetry"
echo "  GRANT ALL PRIVILEGES ON SCHEMA public TO telemetry_user;"
echo "  \\q"
echo "  EOF"
echo ""
echo "Step 3: Verify connection"
echo "  psql -h localhost -U telemetry_user -d fleet_telemetry -c 'SELECT 1;'"
echo ""
echo "Step 4: Build Fleet Telemetry"
echo "  make build"
echo ""
echo "Step 5: Update config file"
echo "  Edit test/integration/postgres_config.json with your paths"
echo ""
echo "Step 6: Run Fleet Telemetry"
echo "  ./fleet-telemetry -config=test/integration/postgres_config.json"
echo ""
echo ""

# Database queries
echo "📊 USEFUL DATABASE QUERIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check table structure:"
echo "  psql -h localhost -U telemetry_user -d fleet_telemetry"
echo "  \\dt"
echo ""
echo "Count records:"
echo "  SELECT COUNT(*) FROM tesla_V;"
echo ""
echo "View recent data:"
echo "  SELECT * FROM tesla_V ORDER BY received_at DESC LIMIT 5;"
echo ""
echo "Query by VIN:"
echo "  SELECT * FROM tesla_V WHERE vin = 'YOUR_VIN' LIMIT 10;"
echo ""
echo ""

# Docker commands
echo "🐳 USEFUL DOCKER COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "View logs:"
echo "  docker-compose -f docker-compose.postgres.yml logs -f"
echo ""
echo "Execute database command:"
echo "  docker exec fleet-telemetry-postgres psql -U telemetry_user -d fleet_telemetry -c 'SELECT COUNT(*) FROM tesla_V;'"
echo ""
echo "Connect to database:"
echo "  docker exec -it fleet-telemetry-postgres psql -U telemetry_user -d fleet_telemetry"
echo ""
echo "Restart services:"
echo "  docker-compose -f docker-compose.postgres.yml restart"
echo ""
echo "Stop without removing:"
echo "  docker-compose -f docker-compose.postgres.yml stop"
echo ""
echo "Remove everything (including data!):"
echo "  docker-compose -f docker-compose.postgres.yml down -v"
echo ""
echo ""

# Documentation
echo "📚 DOCUMENTATION GUIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start with these files (in order):"
echo ""
echo "1. IMPLEMENTATION_SUMMARY.md"
echo "   └─ Overview of what was created"
echo ""
echo "2. DATABASE_SETUP.md"
echo "   └─ Quick reference for both MySQL and PostgreSQL"
echo ""
echo "3. POSTGRES_SETUP.md"
echo "   └─ Detailed PostgreSQL setup and administration"
echo ""
echo "4. POSTGRES_VS_MYSQL.md"
echo "   └─ Comparison to help choose between databases"
echo ""
echo "5. STRUCTURE.md"
echo "   └─ Visual guide to the codebase structure"
echo ""
echo "Detailed information:"
echo "   • /datastore/postgres/README.md - PostgreSQL specifics"
echo "   • /datastore/mysql/README.md - MySQL specifics"
echo ""
echo ""

# Troubleshooting
echo "🆘 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Issue: Docker image not found"
echo "Solution: Build it first: docker build -t fleet-telemetry-integration-tests:latest ."
echo ""
echo "Issue: Port already in use"
echo "Solution: Change port in docker-compose.postgres.yml or stop other services"
echo ""
echo "Issue: Connection refused"
echo "Solution: Check if PostgreSQL is running: docker-compose ps"
echo ""
echo "Issue: Tables not being created"
echo "Solution: Check app logs: docker-compose logs app | grep postgres"
echo ""
echo "Issue: Permission denied"
echo "Solution: Verify database user has correct permissions"
echo ""
echo ""

# Summary
echo "✅ SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 Recommended: Use Docker Compose"
echo "   docker-compose -f docker-compose.postgres.yml up -d"
echo ""
echo "📖 Learn More:"
echo "   cat POSTGRES_SETUP.md"
echo "   cat DATABASE_SETUP.md"
echo ""
echo "🗄️  Also Available: MySQL Connector"
echo "   See /datastore/mysql/README.md for MySQL setup"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""

