apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
spec:
  secretName: {{ printf "%s-tls" (include "fleet-telemetry.fullname" .) | quote }}
  issuerRef:
    name: {{ quote .Values.certificate.issuer }}
    group: cert-manager.io
    kind: ClusterIssuer
  dnsNames: {{ toJson .Values.certificate.dnsNames }}
