apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}-sa
  labels:
    {{- include "fleet-telemetry.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ tpl .Values.service_role_arn . | quote }}
