apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}-internal
  labels:
    prometheus_scrape: "true"
    role: api
    service: fleet-telemetry
  {{- include "fleet-telemetry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceInternal.type }}
  selector:
    role: api
    service: fleet-telemetry
  {{- include "fleet-telemetry.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceInternal.ports | toYaml | nindent 2 -}}
{{- if .Values.serviceInternal.monitor.create }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
  {{- with .Values.serviceInternal.monitor.labels }}
  labels: {{ toJson . }}
  {{- end }}
spec:
  # Select all services in namespace (if they have a metrics port)
  selector:
    matchLabels:
      prometheus_scrape: "true"
      role: api
      service: fleet-telemetry
      {{- include "fleet-telemetry.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 15s
{{- end }}
