// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tesla

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatbuffersStreamAck struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatbuffersStreamAck(buf []byte, offset flatbuffers.UOffsetT) *FlatbuffersStreamAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatbuffersStreamAck{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FlatbuffersStreamAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatbuffersStreamAck) Table() flatbuffers.Table {
	return rcv._tab
}

func FlatbuffersStreamAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FlatbuffersStreamAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
