// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tesla

type Message = byte

const (
	MessageNONE                 Message = 0
	MessageFlatbuffersStream    Message = 4
	MessageFlatbuffersStreamAck Message = 5
)

var EnumNamesMessage = map[Message]string{
	MessageNONE:                 "NONE",
	MessageFlatbuffersStream:    "FlatbuffersStream",
	MessageFlatbuffersStreamAck: "FlatbuffersStreamAck",
}
