// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.33.0
// source: protos/vehicle_connectivity.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectivityEvent represents connection state of the vehicle
type ConnectivityEvent int32

const (
	ConnectivityEvent_UNKNOWN      ConnectivityEvent = 0
	ConnectivityEvent_CONNECTED    ConnectivityEvent = 1
	ConnectivityEvent_DISCONNECTED ConnectivityEvent = 2
)

// Enum value maps for ConnectivityEvent.
var (
	ConnectivityEvent_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECTED",
		2: "DISCONNECTED",
	}
	ConnectivityEvent_value = map[string]int32{
		"UNKNOWN":      0,
		"CONNECTED":    1,
		"DISCONNECTED": 2,
	}
)

func (x ConnectivityEvent) Enum() *ConnectivityEvent {
	p := new(ConnectivityEvent)
	*p = x
	return p
}

func (x ConnectivityEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectivityEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vehicle_connectivity_proto_enumTypes[0].Descriptor()
}

func (ConnectivityEvent) Type() protoreflect.EnumType {
	return &file_protos_vehicle_connectivity_proto_enumTypes[0]
}

func (x ConnectivityEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectivityEvent.Descriptor instead.
func (ConnectivityEvent) EnumDescriptor() ([]byte, []int) {
	return file_protos_vehicle_connectivity_proto_rawDescGZIP(), []int{0}
}

// VehicleConnectivity represents connection status change for the vehicle
type VehicleConnectivity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vin              string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	ConnectionId     string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Status           ConnectivityEvent      `protobuf:"varint,3,opt,name=status,proto3,enum=telemetry.vehicle_connectivity.ConnectivityEvent" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	NetworkInterface string                 `protobuf:"bytes,5,opt,name=network_interface,json=networkInterface,proto3" json:"network_interface,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleConnectivity) Reset() {
	*x = VehicleConnectivity{}
	mi := &file_protos_vehicle_connectivity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleConnectivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleConnectivity) ProtoMessage() {}

func (x *VehicleConnectivity) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_connectivity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleConnectivity.ProtoReflect.Descriptor instead.
func (*VehicleConnectivity) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_connectivity_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleConnectivity) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleConnectivity) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VehicleConnectivity) GetStatus() ConnectivityEvent {
	if x != nil {
		return x.Status
	}
	return ConnectivityEvent_UNKNOWN
}

func (x *VehicleConnectivity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleConnectivity) GetNetworkInterface() string {
	if x != nil {
		return x.NetworkInterface
	}
	return ""
}

var File_protos_vehicle_connectivity_proto protoreflect.FileDescriptor

var file_protos_vehicle_connectivity_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x13, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2a, 0x41, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53, 0x43, 0x4f,
	0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x73, 0x6c, 0x61, 0x6d, 0x6f, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2d, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_vehicle_connectivity_proto_rawDescOnce sync.Once
	file_protos_vehicle_connectivity_proto_rawDescData = file_protos_vehicle_connectivity_proto_rawDesc
)

func file_protos_vehicle_connectivity_proto_rawDescGZIP() []byte {
	file_protos_vehicle_connectivity_proto_rawDescOnce.Do(func() {
		file_protos_vehicle_connectivity_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vehicle_connectivity_proto_rawDescData)
	})
	return file_protos_vehicle_connectivity_proto_rawDescData
}

var file_protos_vehicle_connectivity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_vehicle_connectivity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_vehicle_connectivity_proto_goTypes = []any{
	(ConnectivityEvent)(0),        // 0: telemetry.vehicle_connectivity.ConnectivityEvent
	(*VehicleConnectivity)(nil),   // 1: telemetry.vehicle_connectivity.VehicleConnectivity
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_protos_vehicle_connectivity_proto_depIdxs = []int32{
	0, // 0: telemetry.vehicle_connectivity.VehicleConnectivity.status:type_name -> telemetry.vehicle_connectivity.ConnectivityEvent
	2, // 1: telemetry.vehicle_connectivity.VehicleConnectivity.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_vehicle_connectivity_proto_init() }
func file_protos_vehicle_connectivity_proto_init() {
	if File_protos_vehicle_connectivity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vehicle_connectivity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_vehicle_connectivity_proto_goTypes,
		DependencyIndexes: file_protos_vehicle_connectivity_proto_depIdxs,
		EnumInfos:         file_protos_vehicle_connectivity_proto_enumTypes,
		MessageInfos:      file_protos_vehicle_connectivity_proto_msgTypes,
	}.Build()
	File_protos_vehicle_connectivity_proto = out.File
	file_protos_vehicle_connectivity_proto_rawDesc = nil
	file_protos_vehicle_connectivity_proto_goTypes = nil
	file_protos_vehicle_connectivity_proto_depIdxs = nil
}
