// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protos/vehicle_error.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VehicleErrors is a collection of errors for a single vehicle.
type VehicleErrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*VehicleError        `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleErrors) Reset() {
	*x = VehicleErrors{}
	mi := &file_protos_vehicle_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleErrors) ProtoMessage() {}

func (x *VehicleErrors) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleErrors.ProtoReflect.Descriptor instead.
func (*VehicleErrors) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_error_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleErrors) GetErrors() []*VehicleError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *VehicleErrors) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleErrors) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

// VehicleError is a single error
type VehicleError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleError) Reset() {
	*x = VehicleError{}
	mi := &file_protos_vehicle_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleError) ProtoMessage() {}

func (x *VehicleError) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleError.ProtoReflect.Descriptor instead.
func (*VehicleError) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_error_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleError) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleError) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VehicleError) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_protos_vehicle_error_proto protoreflect.FileDescriptor

const file_protos_vehicle_error_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/vehicle_error.proto\x12\x17telemetry.vehicle_error\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\rVehicleErrors\x12=\n" +
	"\x06errors\x18\x01 \x03(\v2%.telemetry.vehicle_error.VehicleErrorR\x06errors\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x10\n" +
	"\x03vin\x18\x03 \x01(\tR\x03vin\"\xef\x01\n" +
	"\fVehicleError\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12C\n" +
	"\x04tags\x18\x03 \x03(\v2/.telemetry.vehicle_error.VehicleError.TagsEntryR\x04tags\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3"

var (
	file_protos_vehicle_error_proto_rawDescOnce sync.Once
	file_protos_vehicle_error_proto_rawDescData []byte
)

func file_protos_vehicle_error_proto_rawDescGZIP() []byte {
	file_protos_vehicle_error_proto_rawDescOnce.Do(func() {
		file_protos_vehicle_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_vehicle_error_proto_rawDesc), len(file_protos_vehicle_error_proto_rawDesc)))
	})
	return file_protos_vehicle_error_proto_rawDescData
}

var file_protos_vehicle_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_vehicle_error_proto_goTypes = []any{
	(*VehicleErrors)(nil),         // 0: telemetry.vehicle_error.VehicleErrors
	(*VehicleError)(nil),          // 1: telemetry.vehicle_error.VehicleError
	nil,                           // 2: telemetry.vehicle_error.VehicleError.TagsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_protos_vehicle_error_proto_depIdxs = []int32{
	1, // 0: telemetry.vehicle_error.VehicleErrors.errors:type_name -> telemetry.vehicle_error.VehicleError
	3, // 1: telemetry.vehicle_error.VehicleErrors.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: telemetry.vehicle_error.VehicleError.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: telemetry.vehicle_error.VehicleError.tags:type_name -> telemetry.vehicle_error.VehicleError.TagsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_vehicle_error_proto_init() }
func file_protos_vehicle_error_proto_init() {
	if File_protos_vehicle_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_vehicle_error_proto_rawDesc), len(file_protos_vehicle_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_vehicle_error_proto_goTypes,
		DependencyIndexes: file_protos_vehicle_error_proto_depIdxs,
		MessageInfos:      file_protos_vehicle_error_proto_msgTypes,
	}.Build()
	File_protos_vehicle_error_proto = out.File
	file_protos_vehicle_error_proto_goTypes = nil
	file_protos_vehicle_error_proto_depIdxs = nil
}
