// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protos/vehicle_connectivity.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectivityEvent represents connection state of the vehicle
type ConnectivityEvent int32

const (
	ConnectivityEvent_UNKNOWN      ConnectivityEvent = 0
	ConnectivityEvent_CONNECTED    ConnectivityEvent = 1
	ConnectivityEvent_DISCONNECTED ConnectivityEvent = 2
)

// Enum value maps for ConnectivityEvent.
var (
	ConnectivityEvent_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECTED",
		2: "DISCONNECTED",
	}
	ConnectivityEvent_value = map[string]int32{
		"UNKNOWN":      0,
		"CONNECTED":    1,
		"DISCONNECTED": 2,
	}
)

func (x ConnectivityEvent) Enum() *ConnectivityEvent {
	p := new(ConnectivityEvent)
	*p = x
	return p
}

func (x ConnectivityEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectivityEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vehicle_connectivity_proto_enumTypes[0].Descriptor()
}

func (ConnectivityEvent) Type() protoreflect.EnumType {
	return &file_protos_vehicle_connectivity_proto_enumTypes[0]
}

func (x ConnectivityEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectivityEvent.Descriptor instead.
func (ConnectivityEvent) EnumDescriptor() ([]byte, []int) {
	return file_protos_vehicle_connectivity_proto_rawDescGZIP(), []int{0}
}

// VehicleConnectivity represents connection status change for the vehicle
type VehicleConnectivity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vin              string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	ConnectionId     string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Status           ConnectivityEvent      `protobuf:"varint,3,opt,name=status,proto3,enum=telemetry.vehicle_connectivity.ConnectivityEvent" json:"status,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	NetworkInterface string                 `protobuf:"bytes,5,opt,name=network_interface,json=networkInterface,proto3" json:"network_interface,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleConnectivity) Reset() {
	*x = VehicleConnectivity{}
	mi := &file_protos_vehicle_connectivity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleConnectivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleConnectivity) ProtoMessage() {}

func (x *VehicleConnectivity) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_connectivity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleConnectivity.ProtoReflect.Descriptor instead.
func (*VehicleConnectivity) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_connectivity_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleConnectivity) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleConnectivity) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *VehicleConnectivity) GetStatus() ConnectivityEvent {
	if x != nil {
		return x.Status
	}
	return ConnectivityEvent_UNKNOWN
}

func (x *VehicleConnectivity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleConnectivity) GetNetworkInterface() string {
	if x != nil {
		return x.NetworkInterface
	}
	return ""
}

var File_protos_vehicle_connectivity_proto protoreflect.FileDescriptor

const file_protos_vehicle_connectivity_proto_rawDesc = "" +
	"\n" +
	"!protos/vehicle_connectivity.proto\x12\x1etelemetry.vehicle_connectivity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x13VehicleConnectivity\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12I\n" +
	"\x06status\x18\x03 \x01(\x0e21.telemetry.vehicle_connectivity.ConnectivityEventR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11network_interface\x18\x05 \x01(\tR\x10networkInterface*A\n" +
	"\x11ConnectivityEvent\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02B/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3"

var (
	file_protos_vehicle_connectivity_proto_rawDescOnce sync.Once
	file_protos_vehicle_connectivity_proto_rawDescData []byte
)

func file_protos_vehicle_connectivity_proto_rawDescGZIP() []byte {
	file_protos_vehicle_connectivity_proto_rawDescOnce.Do(func() {
		file_protos_vehicle_connectivity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_vehicle_connectivity_proto_rawDesc), len(file_protos_vehicle_connectivity_proto_rawDesc)))
	})
	return file_protos_vehicle_connectivity_proto_rawDescData
}

var file_protos_vehicle_connectivity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_vehicle_connectivity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_vehicle_connectivity_proto_goTypes = []any{
	(ConnectivityEvent)(0),        // 0: telemetry.vehicle_connectivity.ConnectivityEvent
	(*VehicleConnectivity)(nil),   // 1: telemetry.vehicle_connectivity.VehicleConnectivity
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_protos_vehicle_connectivity_proto_depIdxs = []int32{
	0, // 0: telemetry.vehicle_connectivity.VehicleConnectivity.status:type_name -> telemetry.vehicle_connectivity.ConnectivityEvent
	2, // 1: telemetry.vehicle_connectivity.VehicleConnectivity.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_vehicle_connectivity_proto_init() }
func file_protos_vehicle_connectivity_proto_init() {
	if File_protos_vehicle_connectivity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_vehicle_connectivity_proto_rawDesc), len(file_protos_vehicle_connectivity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_vehicle_connectivity_proto_goTypes,
		DependencyIndexes: file_protos_vehicle_connectivity_proto_depIdxs,
		EnumInfos:         file_protos_vehicle_connectivity_proto_enumTypes,
		MessageInfos:      file_protos_vehicle_connectivity_proto_msgTypes,
	}.Build()
	File_protos_vehicle_connectivity_proto = out.File
	file_protos_vehicle_connectivity_proto_goTypes = nil
	file_protos_vehicle_connectivity_proto_depIdxs = nil
}
