// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protos/vehicle_metric.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VehicleMetrics is a collection of metrics for a single vehicle.
type VehicleMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleMetrics) Reset() {
	*x = VehicleMetrics{}
	mi := &file_protos_vehicle_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMetrics) ProtoMessage() {}

func (x *VehicleMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMetrics.ProtoReflect.Descriptor instead.
func (*VehicleMetrics) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_metric_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleMetrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *VehicleMetrics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleMetrics) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

// Metric is a single metric value with a name, tags, and a value.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_protos_vehicle_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_metric_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protos_vehicle_metric_proto protoreflect.FileDescriptor

const file_protos_vehicle_metric_proto_rawDesc = "" +
	"\n" +
	"\x1bprotos/vehicle_metric.proto\x12\x19telemetry.vehicle_metrics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\x0eVehicleMetrics\x12;\n" +
	"\ametrics\x18\x01 \x03(\v2!.telemetry.vehicle_metrics.MetricR\ametrics\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x10\n" +
	"\x03vin\x18\x03 \x01(\tR\x03vin\"\xac\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\x04tags\x18\x02 \x03(\v2+.telemetry.vehicle_metrics.Metric.TagsEntryR\x04tags\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3"

var (
	file_protos_vehicle_metric_proto_rawDescOnce sync.Once
	file_protos_vehicle_metric_proto_rawDescData []byte
)

func file_protos_vehicle_metric_proto_rawDescGZIP() []byte {
	file_protos_vehicle_metric_proto_rawDescOnce.Do(func() {
		file_protos_vehicle_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_vehicle_metric_proto_rawDesc), len(file_protos_vehicle_metric_proto_rawDesc)))
	})
	return file_protos_vehicle_metric_proto_rawDescData
}

var file_protos_vehicle_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_vehicle_metric_proto_goTypes = []any{
	(*VehicleMetrics)(nil),        // 0: telemetry.vehicle_metrics.VehicleMetrics
	(*Metric)(nil),                // 1: telemetry.vehicle_metrics.Metric
	nil,                           // 2: telemetry.vehicle_metrics.Metric.TagsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_protos_vehicle_metric_proto_depIdxs = []int32{
	1, // 0: telemetry.vehicle_metrics.VehicleMetrics.metrics:type_name -> telemetry.vehicle_metrics.Metric
	3, // 1: telemetry.vehicle_metrics.VehicleMetrics.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: telemetry.vehicle_metrics.Metric.tags:type_name -> telemetry.vehicle_metrics.Metric.TagsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_vehicle_metric_proto_init() }
func file_protos_vehicle_metric_proto_init() {
	if File_protos_vehicle_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_vehicle_metric_proto_rawDesc), len(file_protos_vehicle_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_vehicle_metric_proto_goTypes,
		DependencyIndexes: file_protos_vehicle_metric_proto_depIdxs,
		MessageInfos:      file_protos_vehicle_metric_proto_msgTypes,
	}.Build()
	File_protos_vehicle_metric_proto = out.File
	file_protos_vehicle_metric_proto_goTypes = nil
	file_protos_vehicle_metric_proto_depIdxs = nil
}
