// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protos/vehicle_alert.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audience the target audience for the alert.
type Audience int32

const (
	Audience_Unknown    Audience = 0
	Audience_Customer   Audience = 1
	Audience_Service    Audience = 2
	Audience_ServiceFix Audience = 3
)

// Enum value maps for Audience.
var (
	Audience_name = map[int32]string{
		0: "Unknown",
		1: "Customer",
		2: "Service",
		3: "ServiceFix",
	}
	Audience_value = map[string]int32{
		"Unknown":    0,
		"Customer":   1,
		"Service":    2,
		"ServiceFix": 3,
	}
)

func (x Audience) Enum() *Audience {
	p := new(Audience)
	*p = x
	return p
}

func (x Audience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Audience) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vehicle_alert_proto_enumTypes[0].Descriptor()
}

func (Audience) Type() protoreflect.EnumType {
	return &file_protos_vehicle_alert_proto_enumTypes[0]
}

func (x Audience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Audience.Descriptor instead.
func (Audience) EnumDescriptor() ([]byte, []int) {
	return file_protos_vehicle_alert_proto_rawDescGZIP(), []int{0}
}

// VehicleAlerts is a collection of recent alerts.
type VehicleAlerts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*VehicleAlert        `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleAlerts) Reset() {
	*x = VehicleAlerts{}
	mi := &file_protos_vehicle_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleAlerts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleAlerts) ProtoMessage() {}

func (x *VehicleAlerts) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleAlerts.ProtoReflect.Descriptor instead.
func (*VehicleAlerts) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_alert_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleAlerts) GetAlerts() []*VehicleAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *VehicleAlerts) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VehicleAlerts) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

// VehicleAlert is a single alert and is active if ended_at is nil.
type VehicleAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Audiences     []Audience             `protobuf:"varint,2,rep,packed,name=audiences,proto3,enum=telemetry.vehicle_alerts.Audience" json:"audiences,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleAlert) Reset() {
	*x = VehicleAlert{}
	mi := &file_protos_vehicle_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleAlert) ProtoMessage() {}

func (x *VehicleAlert) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicle_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleAlert.ProtoReflect.Descriptor instead.
func (*VehicleAlert) Descriptor() ([]byte, []int) {
	return file_protos_vehicle_alert_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleAlert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleAlert) GetAudiences() []Audience {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *VehicleAlert) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *VehicleAlert) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

var File_protos_vehicle_alert_proto protoreflect.FileDescriptor

const file_protos_vehicle_alert_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/vehicle_alert.proto\x12\x18telemetry.vehicle_alerts\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\rVehicleAlerts\x12>\n" +
	"\x06alerts\x18\x01 \x03(\v2&.telemetry.vehicle_alerts.VehicleAlertR\x06alerts\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x10\n" +
	"\x03vin\x18\x03 \x01(\tR\x03vin\"\xd6\x01\n" +
	"\fVehicleAlert\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\taudiences\x18\x02 \x03(\x0e2\".telemetry.vehicle_alerts.AudienceR\taudiences\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt*B\n" +
	"\bAudience\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\bCustomer\x10\x01\x12\v\n" +
	"\aService\x10\x02\x12\x0e\n" +
	"\n" +
	"ServiceFix\x10\x03B/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3"

var (
	file_protos_vehicle_alert_proto_rawDescOnce sync.Once
	file_protos_vehicle_alert_proto_rawDescData []byte
)

func file_protos_vehicle_alert_proto_rawDescGZIP() []byte {
	file_protos_vehicle_alert_proto_rawDescOnce.Do(func() {
		file_protos_vehicle_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_vehicle_alert_proto_rawDesc), len(file_protos_vehicle_alert_proto_rawDesc)))
	})
	return file_protos_vehicle_alert_proto_rawDescData
}

var file_protos_vehicle_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_vehicle_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_vehicle_alert_proto_goTypes = []any{
	(Audience)(0),                 // 0: telemetry.vehicle_alerts.Audience
	(*VehicleAlerts)(nil),         // 1: telemetry.vehicle_alerts.VehicleAlerts
	(*VehicleAlert)(nil),          // 2: telemetry.vehicle_alerts.VehicleAlert
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_protos_vehicle_alert_proto_depIdxs = []int32{
	2, // 0: telemetry.vehicle_alerts.VehicleAlerts.alerts:type_name -> telemetry.vehicle_alerts.VehicleAlert
	3, // 1: telemetry.vehicle_alerts.VehicleAlerts.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: telemetry.vehicle_alerts.VehicleAlert.audiences:type_name -> telemetry.vehicle_alerts.Audience
	3, // 3: telemetry.vehicle_alerts.VehicleAlert.started_at:type_name -> google.protobuf.Timestamp
	3, // 4: telemetry.vehicle_alerts.VehicleAlert.ended_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_vehicle_alert_proto_init() }
func file_protos_vehicle_alert_proto_init() {
	if File_protos_vehicle_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_vehicle_alert_proto_rawDesc), len(file_protos_vehicle_alert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_vehicle_alert_proto_goTypes,
		DependencyIndexes: file_protos_vehicle_alert_proto_depIdxs,
		EnumInfos:         file_protos_vehicle_alert_proto_enumTypes,
		MessageInfos:      file_protos_vehicle_alert_proto_msgTypes,
	}.Build()
	File_protos_vehicle_alert_proto = out.File
	file_protos_vehicle_alert_proto_goTypes = nil
	file_protos_vehicle_alert_proto_depIdxs = nil
}
