# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_connector_service.proto

require 'google/protobuf'


descriptor_data = "\n\x1c\x64\x61ta_connector_service.proto\x12\x14telemetry.connectors\" \n\x11VinAllowedRequest\x12\x0b\n\x03Vin\x18\x01 \x01(\t\"%\n\x12VinAllowedResponse\x12\x0f\n\x07\x41llowed\x18\x01 \x01(\x08\x32q\n\x0eVehicleService\x12_\n\nVinAllowed\x12\'.telemetry.connectors.VinAllowedRequest\x1a(.telemetry.connectors.VinAllowedResponseB/Z-github.com/teslamotors/fleet-telemetry/protosb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Telemetry
  module Connectors
    VinAllowedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.connectors.VinAllowedRequest").msgclass
    VinAllowedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("telemetry.connectors.VinAllowedResponse").msgclass
  end
end
