# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: data_connector_service.proto for package 'telemetry.connectors'

require 'grpc'
require 'data_connector_service_pb'

module Telemetry
  module Connectors
    module VehicleService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'telemetry.connectors.VehicleService'

        rpc :VinAllowed, ::Telemetry::Connectors::VinAllowedRequest, ::Telemetry::Connectors::VinAllowedResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
